services:
  app:
    build:
      context: .
    container_name: api
    ports:
        - "8000:8000"
    env_file: .env
    networks:
      - ingestion_net
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - ingestion_net

volumes:
  qdrant_storage:

networks:
  ingestion_net:
